### ISSUE TITLE
Interacting with game components (e.g. bumpers)

### ISSUE THREAD

**Issue by KimikoMcGirr** [Jessime/MazeDay2017#7]
http://www.vpforums.org/Tutorials/Sounds/SndLib1.html

**Comment by KimikoMcGirr** [comment]
we liked 'flipper up 11'

**Comment by Jessime** [comment]
We need pitch noises for bins.

**Comment by Jessime** [comment]
I talked to Kathleen about this. Hopefully she can pull through and get us recordings of well separated notes.

**Comment by Jessime** [comment]
We have the sound files, and they've been edited. Now we just have to implement this.

**Comment by Jessime** [comment]
I need to test timing when there's no video, but this is implemented.
